// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: analytics.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

/** User Productivity */
export interface GetUserProductivityRequest {
  userId: string;
  startDate: string;
  endDate: string;
  /** DAY, WEEK, MONTH */
  granularity: string;
}

export interface UserProductivityData {
  date: string;
  tasksCreated: number;
  tasksCompleted: number;
  tasksInProgress: number;
  tasksOverdue: number;
  averageCompletionTime: number;
  productivityScore: number;
}

export interface UserProductivityResponse {
  data: UserProductivityData[];
  summary: UserProductivitySummary | undefined;
}

export interface UserProductivitySummary {
  totalTasksCreated: number;
  totalTasksCompleted: number;
  averageProductivityScore: number;
  completionRate: number;
  averageCompletionTime: number;
}

/** Task Metrics */
export interface GetTaskMetricsRequest {
  startDate: string;
  endDate: string;
  /** DAY, WEEK, MONTH */
  granularity: string;
}

export interface TaskMetricsData {
  date: string;
  totalTasks: number;
  tasksCreated: number;
  tasksCompleted: number;
  tasksInProgress: number;
  tasksInReview: number;
  tasksCancelled: number;
  tasksOverdue: number;
  completionRate: number;
  averageCompletionTime: number;
}

export interface TaskMetricsResponse {
  data: TaskMetricsData[];
  summary: TaskMetricsSummary | undefined;
}

export interface TaskMetricsSummary {
  totalTasks: number;
  totalCompleted: number;
  overallCompletionRate: number;
  averageCompletionTime: number;
}

/** Priority Distribution */
export interface GetPriorityDistributionRequest {
  startDate: string;
  endDate: string;
}

export interface PriorityDistributionData {
  date: string;
  low: number;
  medium: number;
  high: number;
  urgent: number;
}

export interface PriorityDistributionResponse {
  data: PriorityDistributionData[];
  summary: PriorityDistributionSummary | undefined;
}

export interface PriorityDistributionSummary {
  totalLow: number;
  totalMedium: number;
  totalHigh: number;
  totalUrgent: number;
}

/** Status Distribution */
export interface GetStatusDistributionRequest {
  startDate: string;
  endDate: string;
}

export interface StatusDistributionData {
  date: string;
  todo: number;
  inProgress: number;
  review: number;
  completed: number;
  cancelled: number;
}

export interface StatusDistributionResponse {
  data: StatusDistributionData[];
  summary: StatusDistributionSummary | undefined;
}

export interface StatusDistributionSummary {
  totalTodo: number;
  totalInProgress: number;
  totalReview: number;
  totalCompleted: number;
  totalCancelled: number;
}

/** User Activity Heatmap */
export interface GetUserActivityHeatmapRequest {
  userId: string;
  startDate: string;
  endDate: string;
}

export interface HeatmapDataPoint {
  date: string;
  /** 0-23 */
  hour: number;
  activityCount: number;
}

export interface UserActivityHeatmapResponse {
  data: HeatmapDataPoint[];
  totalActivities: number;
  peakHour: number;
}

export interface AnalyticsServiceClient {
  getUserProductivity(request: GetUserProductivityRequest): Observable<UserProductivityResponse>;

  getTaskMetrics(request: GetTaskMetricsRequest): Observable<TaskMetricsResponse>;

  getPriorityDistribution(request: GetPriorityDistributionRequest): Observable<PriorityDistributionResponse>;

  getStatusDistribution(request: GetStatusDistributionRequest): Observable<StatusDistributionResponse>;

  getUserActivityHeatmap(request: GetUserActivityHeatmapRequest): Observable<UserActivityHeatmapResponse>;
}

export interface AnalyticsServiceController {
  getUserProductivity(
    request: GetUserProductivityRequest,
  ): Promise<UserProductivityResponse> | Observable<UserProductivityResponse> | UserProductivityResponse;

  getTaskMetrics(
    request: GetTaskMetricsRequest,
  ): Promise<TaskMetricsResponse> | Observable<TaskMetricsResponse> | TaskMetricsResponse;

  getPriorityDistribution(
    request: GetPriorityDistributionRequest,
  ): Promise<PriorityDistributionResponse> | Observable<PriorityDistributionResponse> | PriorityDistributionResponse;

  getStatusDistribution(
    request: GetStatusDistributionRequest,
  ): Promise<StatusDistributionResponse> | Observable<StatusDistributionResponse> | StatusDistributionResponse;

  getUserActivityHeatmap(
    request: GetUserActivityHeatmapRequest,
  ): Promise<UserActivityHeatmapResponse> | Observable<UserActivityHeatmapResponse> | UserActivityHeatmapResponse;
}

export function AnalyticsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUserProductivity",
      "getTaskMetrics",
      "getPriorityDistribution",
      "getStatusDistribution",
      "getUserActivityHeatmap",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AnalyticsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AnalyticsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ANALYTICS_SERVICE_NAME = "AnalyticsService";
