// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: file.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface UploadFileRequest {
  content: Uint8Array;
  filename: string;
  mimeType: string;
  uploadedBy: string;
  taskId?: string | undefined;
  description?: string | undefined;
}

export interface UploadFileResponse {
  id: string;
  filename: string;
  url: string;
  thumbnailUrl?: string | undefined;
  size: number;
  message: string;
}

export interface GetFileRequest {
  id: string;
}

export interface GetFileResponse {
  id: string;
  filename: string;
  originalName: string;
  mimeType: string;
  size: number;
  url: string;
  thumbnailUrl?: string | undefined;
  uploadedBy: string;
  taskId?: string | undefined;
  description?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface DeleteFileRequest {
  id: string;
  userId: string;
}

export interface DeleteFileResponse {
  success: boolean;
  message: string;
}

export interface ListFilesRequest {
  page: number;
  limit: number;
}

export interface GetFilesByTaskRequest {
  taskId: string;
  page: number;
  limit: number;
}

export interface GetFilesByUserRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface ListFilesResponse {
  files: FileInfo[];
  total: number;
  page: number;
  limit: number;
}

export interface FileInfo {
  id: string;
  filename: string;
  originalName: string;
  mimeType: string;
  size: number;
  url: string;
  thumbnailUrl?: string | undefined;
  uploadedBy: string;
  taskId?: string | undefined;
  description?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface FileServiceClient {
  uploadFile(request: UploadFileRequest): Observable<UploadFileResponse>;

  getFile(request: GetFileRequest): Observable<GetFileResponse>;

  deleteFile(request: DeleteFileRequest): Observable<DeleteFileResponse>;

  listFiles(request: ListFilesRequest): Observable<ListFilesResponse>;

  getFilesByTask(request: GetFilesByTaskRequest): Observable<ListFilesResponse>;

  getFilesByUser(request: GetFilesByUserRequest): Observable<ListFilesResponse>;
}

export interface FileServiceController {
  uploadFile(
    request: UploadFileRequest,
  ): Promise<UploadFileResponse> | Observable<UploadFileResponse> | UploadFileResponse;

  getFile(request: GetFileRequest): Promise<GetFileResponse> | Observable<GetFileResponse> | GetFileResponse;

  deleteFile(
    request: DeleteFileRequest,
  ): Promise<DeleteFileResponse> | Observable<DeleteFileResponse> | DeleteFileResponse;

  listFiles(request: ListFilesRequest): Promise<ListFilesResponse> | Observable<ListFilesResponse> | ListFilesResponse;

  getFilesByTask(
    request: GetFilesByTaskRequest,
  ): Promise<ListFilesResponse> | Observable<ListFilesResponse> | ListFilesResponse;

  getFilesByUser(
    request: GetFilesByUserRequest,
  ): Promise<ListFilesResponse> | Observable<ListFilesResponse> | ListFilesResponse;
}

export function FileServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "uploadFile",
      "getFile",
      "deleteFile",
      "listFiles",
      "getFilesByTask",
      "getFilesByUser",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FileService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FileService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FILE_SERVICE_NAME = "FileService";
