// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: task.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface CreateTaskRequest {
  title: string;
  description: string;
  priority: string;
  status: string;
  dueDate: string;
  createdBy: string;
  assignedTo: string;
}

export interface GetTaskRequest {
  id: string;
  userId: string;
}

export interface GetTasksRequest {
  page: number;
  limit: number;
  status: string;
  priority: string;
}

export interface UpdateTaskRequest {
  id: string;
  title: string;
  description: string;
  priority: string;
  status: string;
  dueDate: string;
  assignedTo: string;
  userId: string;
}

export interface DeleteTaskRequest {
  id: string;
  userId: string;
}

export interface AssignTaskRequest {
  id: string;
  assignedTo: string;
}

export interface UpdateTaskStatusRequest {
  id: string;
  status: string;
}

export interface GetUserTasksRequest {
  userId: string;
  page: number;
  limit: number;
  status: string;
  priority: string;
  search: string;
}

export interface TaskResponse {
  task: Task | undefined;
}

export interface TasksResponse {
  tasks: Task[];
  total: number;
  page: number;
  limit: number;
}

export interface DeleteTaskResponse {
  message: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  priority: string;
  status: string;
  dueDate: string;
  createdBy: string;
  assignedTo: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetDashboardDataRequest {
  userId: string;
  recentTasksLimit: number;
}

export interface GetDashboardDataResponse {
  recentTasks: Task[];
  totalCount: number;
  todoCount: number;
  inProgressCount: number;
  reviewCount: number;
  completedCount: number;
  cancelledCount: number;
}

export interface TaskServiceClient {
  createTask(request: CreateTaskRequest): Observable<TaskResponse>;

  getTask(request: GetTaskRequest): Observable<TaskResponse>;

  getTasks(request: GetTasksRequest): Observable<TasksResponse>;

  updateTask(request: UpdateTaskRequest): Observable<TaskResponse>;

  deleteTask(request: DeleteTaskRequest): Observable<DeleteTaskResponse>;

  assignTask(request: AssignTaskRequest): Observable<TaskResponse>;

  updateTaskStatus(request: UpdateTaskStatusRequest): Observable<TaskResponse>;

  getUserTasks(request: GetUserTasksRequest): Observable<TasksResponse>;

  getDashboardData(request: GetDashboardDataRequest): Observable<GetDashboardDataResponse>;
}

export interface TaskServiceController {
  createTask(request: CreateTaskRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  getTask(request: GetTaskRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  getTasks(request: GetTasksRequest): Promise<TasksResponse> | Observable<TasksResponse> | TasksResponse;

  updateTask(request: UpdateTaskRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  deleteTask(
    request: DeleteTaskRequest,
  ): Promise<DeleteTaskResponse> | Observable<DeleteTaskResponse> | DeleteTaskResponse;

  assignTask(request: AssignTaskRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  updateTaskStatus(request: UpdateTaskStatusRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  getUserTasks(request: GetUserTasksRequest): Promise<TasksResponse> | Observable<TasksResponse> | TasksResponse;

  getDashboardData(
    request: GetDashboardDataRequest,
  ): Promise<GetDashboardDataResponse> | Observable<GetDashboardDataResponse> | GetDashboardDataResponse;
}

export function TaskServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTask",
      "getTask",
      "getTasks",
      "updateTask",
      "deleteTask",
      "assignTask",
      "updateTaskStatus",
      "getUserTasks",
      "getDashboardData",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TASK_SERVICE_NAME = "TaskService";
